Repository abaig08/AMS, pull requests merged in 2024-06, with the labels that each got.

#19 bug/2-deploy-error: Removed bug in firebase.json
  firebase.json
  src/components/Button.jsx
  src/components/EditModal.jsx
  src/components/Modal.jsx
  src/components/Recordstable.jsx
  src/components/StyledDatePicker.jsx
  src/components/UserPunchin.jsx
  src/components/Userprofile.jsx
  src/components/admin/CreateEmployeeModal.jsx
Labels: bug

#20 bug/2-deploy-error
  build/assets/flipopay-logo-Ddz3lX61.png
  build/assets/flipopay_logo-CMERhajz.png
  build/assets/index-DBBDpCyK.css
  build/assets/index-JN3wp5jo.js
  build/index.html
  build/vite.svg
  firebase.json
  package-lock.json
  src/components/EditModal.jsx
  vite.config.js
  y/index.html
Labels: bug

#28 feat/15-checks-for-punchin: Added checks
  build/assets/index-CvwwFdbP.js
  build/assets/index-lYiU_UVl.js
  build/index.html
  src/App.jsx
  src/components/UserPunchin.jsx
  src/pages/UserPage.jsx
  src/utils/locationMethods.js
Labels: enhancement

#30 feat14-add-icon: Favicon and README Updation
  README.md
  index.html
  public/flipopay-logo.svg
  public/vite.svg
Labels: documentation, enhancement

#24 fetched datas from firestore db
  src/components/Recordstable.jsx
  src/components/admin/CreateEmployeeModal.jsx
  src/components/auth/Login.jsx
Labels: enhancement

#34 feat/12-bug
  src/components/Recordstable.jsx
Labels: duplicate

#36 feat/13-create-404
  build/assets/index-B9wssT9v.js
  build/assets/index-BXzx7WsE.js
  build/assets/index-BnRqOaYt.css
  build/assets/index-Cf3Jttwy.js
  build/assets/index-ayBQWL27.css
  build/index.html
  package-lock.json
  package.json
  src/App.jsx
  src/assets/react.svg
  src/components/Header.jsx
  src/components/Recordstable.jsx
  src/components/SideNavbar.jsx
  src/components/UserPunchin.jsx
  src/components/UserTable.jsx
  src/components/Userprofile.jsx
  src/pages/NotFoundPage.jsx
  src/pages/UserPage.jsx
Labels: enhancement

#39 feat/19-minor-integrations
  src/components/modals/CreateEmployeeModal.jsx
Labels: duplicate

#40 feat/20-map-status
  src/components/UserPunchin.jsx
  src/components/modals/CreateEmployeeModal.jsx
  src/components/table/Recordstable.jsx
  src/utils/constants.js
  src/utils/dateMethods.js
  src/utils/statusMethods.js
  src/utils/validationMethods.js
Labels: enhancement
